def add(a, b): print(a + b)
def subt(a, b): pritn(a - b)
def multi(a, b): print(a * b)
def divi(a, b):
  if(b == 0): print(None)
  else: print(a / b)
print('1. Add\n2. Subtract\n3. Multiply\n4. Divide\n5. Exit\nEnter your Choice:')
ch = int(input())
if(ch == 5): exit(0)
a, b = int(input()), int(input())
if(ch == 1): add(a, b)
if(ch == 2): subt(a, b)
if(ch == 3): multi(a, b)
if(ch == 4): divi(a, b)
